version: "2"
engines:
  phpcs:
  enabled: true
  channel: "stable"
  config:
    standard: PSR2
  phpmd:
    enabled: true
    config:
    rulesets: "cleancode, codesize, controversal, design, naming, unusedcode"
  phpstan:
  enabled: true
  level: 5
  
