name: PHP CI with CodeClimate

on:
  push:
    branches:
      - main       # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main       # Trigger the workflow on pull request targeting the 'main' branch

jobs:
  analyze:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Specify PHP version here

      # Install dependencies (e.g., Composer)
      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
          composer install --no-progress --no-suggest

      # Install CodeClimate CLI
      - name: Install CodeClimate CLI
        run: |
          curl -L https://github.com/codeclimate/codeclimate/releases/download/v0.88.0/codeclimate-linux-amd64-0.88.0.tar.gz -o codeclimate.tar.gz
          tar xzf codeclimate.tar.gz
          mv codeclimate /usr/local/bin/codeclimate

      # Run CodeClimate analysis
      - name: Run CodeClimate analysis
        run: |
          codeclimate analyze
