version: "2"
jobs:
  analyze:
    docker:
      - image: "php:7.4-cli"  # Use the PHP Docker image for analysis
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y git unzip libpng-dev libjpeg-dev libfreetype6-dev
            docker-php-ext-configure gd --with-freetype --with-jpeg
            docker-php-ext-install gd
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
            composer install --prefer-dist --no-progress --no-suggest
      - run:
          name: Run CodeClimate Analysis
          command: |
            curl -L https://github.com/codeclimate/codeclimate/releases/download/v0.88.0/codeclimate-linux-amd64-0.88.0.tar.gz -o codeclimate.tar.gz
            tar xzf codeclimate.tar.gz
            ./codeclimate analyze

  test:
    docker:
      - image: "php:7.4-cli"  # Use the PHP Docker image for running tests
    steps:
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y git unzip
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
            composer install --prefer-dist --no-progress --no-suggest
      - run:
          name: Run PHP Tests
          command: |
            ./vendor/bin/phpunit --configuration phpunit.xml

workflows:
  version: "2"
  default:
    - analyze
    - test
